MassNumber = float(input("Enter Mass Number: "))
Electrons = float(input("Enter Electron Amount: "))
ProtonNumber = float(input("Enter Proton Amount: "))
NeutronNumber = float(input("Enter Neutron Amount: "))
print("-------------------------")
print ("Mnucleus =", ((MassNumber * float(1.66054E-27)) - (Electrons * float(9.10915E-31))), ("kg"))
print ("Mprotons =", ((ProtonNumber * float(1.67262E-27)) + (NeutronNumber * float(1.67495E-27))), ("kg"))
print ("Mass Defect =", ((MassNumber * float(1.66054E-27)) - (Electrons * float(9.10915E-31))) - (ProtonNumber * float(1.67262E-27)) + (NeutronNumber * float(1.67495E-27))), ("kg")
input()
