MassNumber = float(input("Enter Mass Number: "))
MassFormula = float(1.66054E-27)
Electrons = float(input("Enter Electron Amount: "))
ElectronsFormula = float(9.10915E-31)
Mnucleus = (MassNumber * MassFormula) - (Electrons * ElectronsFormula)
ProtonNumber = float(input("Enter Proton Amount: "))
ProtonFormula = float(1.67262E-27)
NeutronNumber = float(input("Enter Neutron Amount: "))
NeutronFormula = float(1.67495E-27)
Mprotons = (ProtonNumber * ProtonFormula) + (NeutronNumber * NeutronFormula)
Answer = Mnucleus - Mprotons
print("-------------------------")
print ("Mnucleus =", (Mnucleus), ("kg"))
print ("Mprotons =", (Mprotons), ("kg"))
print ("Mass Defect = ", (Answer) ("kg"))
input()
